# Site settings
title: AMontero Abogados
email: info@amonteroabogados.com
description: > # this means to ignore newlines until next element
  Description of website
keywords: >
  abogados, valencia, etc
baseurl: ""
url: "http://localhost:3000"
exclude: ["_dev",
         ".git",
         ".gitignore",
         "gulpfile.js",
         "node_modules",
         "package.json"]
